apiVersion: apps/v1
kind: Deployment
metadata:
  name: ynab-bot
spec:
  selector:
    matchLabels:
      app: ynab-bot
  template:
    metadata:
      labels:
        app: ynab-bot
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: app
        image: ynab-bot-amd64:1.0
        env:
        - name: BOT_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        # Readiness and liveness
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: app-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /v1/readiness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /v1/liveness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ynab-bot
spec:
  selector:
    service: ynab-bot
  ports:
  - name: app-debug
    port: 4000
    targetPort: app-debug