// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInvalidSMSer is an autogenerated mock type for the InvalidSMSer type
type MockInvalidSMSer struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, invalidSMS
func (_m *MockInvalidSMSer) Save(ctx context.Context, invalidSMS *InvalidSmsRecord) error {
	ret := _m.Called(ctx, invalidSMS)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *InvalidSmsRecord) error); ok {
		r0 = rf(ctx, invalidSMS)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
