// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTXNer is an autogenerated mock type for the TXNer type
type MockTXNer struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, newTxn
func (_m *MockTXNer) Save(ctx context.Context, newTxn *NewTXNRecord) error {
	ret := _m.Called(ctx, newTxn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *NewTXNRecord) error); ok {
		r0 = rf(ctx, newTxn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
