http:
  port: 5001
  readTimeOut: 10s
  writeTimeOut: 10s
  shutdownTimeout: 10s

telegram:
  token: "TOKEN"
  debug: true

mongo:
  name: "ynab-helper"
  uri: "mongodb://mongo:27017"
  user: "root"
  password: "root"
